// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOG8h7W2rX3CSQ1OpblzQlVx19WoczsU',
    appId: '1:753284363657:web:64c312465b8e1ff0765d58',
    messagingSenderId: '753284363657',
    projectId: 'mob3uasklp12',
    authDomain: 'mob3uasklp12.firebaseapp.com',
    storageBucket: 'mob3uasklp12.firebasestorage.app',
    measurementId: 'G-R1705VT4XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodAAMHDBCy1IwDqzKzPGlwFffb1KrWAA',
    appId: '1:753284363657:android:ff2f0fbbab06ec14765d58',
    messagingSenderId: '753284363657',
    projectId: 'mob3uasklp12',
    storageBucket: 'mob3uasklp12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncjHkf1BHwbzkENkNO9PYIuaJPKxZvX8',
    appId: '1:753284363657:ios:0746812365750ff0765d58',
    messagingSenderId: '753284363657',
    projectId: 'mob3uasklp12',
    storageBucket: 'mob3uasklp12.firebasestorage.app',
    iosBundleId: 'com.example.mob3UbgKelompok12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCncjHkf1BHwbzkENkNO9PYIuaJPKxZvX8',
    appId: '1:753284363657:ios:0746812365750ff0765d58',
    messagingSenderId: '753284363657',
    projectId: 'mob3uasklp12',
    storageBucket: 'mob3uasklp12.firebasestorage.app',
    iosBundleId: 'com.example.mob3UbgKelompok12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXOG8h7W2rX3CSQ1OpblzQlVx19WoczsU',
    appId: '1:753284363657:web:1bfe12bbefc89ffe765d58',
    messagingSenderId: '753284363657',
    projectId: 'mob3uasklp12',
    authDomain: 'mob3uasklp12.firebaseapp.com',
    storageBucket: 'mob3uasklp12.firebasestorage.app',
    measurementId: 'G-Y9BL61EDFB',
  );
}
